services:
  blo_db:
    image: mongo:8.0.4
    container_name: blo_mongodb
    volumes:
      - ./mongoDB_data:/data/db
      - ./mongoDB_config:/data/configdb
      - ./mongoDB_backups:/backups
    ports:
      - "${MONGODB_PORT}:27017"
  blo_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: blogscraper:latest
    container_name: blo_backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend/src:/app/src
      - ./data:/app/data
    environment:
      BACKEND_PORT: "${BACKEND_PORT:-8000}"
      MONGODB_PORT: "${MONGODB_PORT:-27017}"
    command: [
      "poetry", "run", "uvicorn", "blogscraper.main:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload"
    ]
    depends_on:
      - blo_db
