/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Blog Scraper
 * Summarize interesting recent AI blog posts
 * OpenAPI spec version: 1.0
 */

export type DeleteGoogleDocDeleteGoogleDocPostParams = {
doc_id: string;
name: string;
};
