/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Blog Scraper
 * Summarize interesting recent AI blog posts
 * OpenAPI spec version: 1.0
 */

export type GoogleDocFromDocumentsGoogleDocFromDocumentsGetParams = {
/**
 * Start date (inclusive)
 */
start_date: string;
/**
 * End date (inclusive)
 */
end_date: string;
/**
 * Filter by source
 */
source?: string | null;
/**
 * Regex to match in post content
 */
match_string?: string | null;
};
