name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Set the default working directory to 'backend'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --extras dev

      - name: Run linters
        run: |
          poetry run black --check .
          poetry run isort --check-only .
          poetry run ruff check .
          poetry run pyright .
          poetry run mypy .

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=.

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
