name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --extras dev
      - name: Run linters
        run: |
          poetry run black --check .
          poetry run isort --check-only .
          poetry run ruff check .
          poetry run pyright .
          poetry run mypy .
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=.
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
